### ISSUE TITLE
需要获取权限有点鸡肋

### ISSUE THREAD

**Issue by fuhongliang** [bboylin/UniversalToast#22]

**Comment by bboylin** [comment]
要点击必须要权限。另外，他那个怎么和我的这么像。。。 邓林 西安交通大学  -  Android开发工程师 邮箱：bboylin24@gmail.com 17629212536 签名由 网易邮箱大师 定制 在2018年07月18日 10:27，Tony Fu 写道： 能实现不需要获取权限就直接Toast么？想这个库一样，地址 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by fuhongliang** [comment]
那个是我在其他地方找的，直接继承了Toast，不需要权限也能实现你那样的效果

**Comment by bboylin** [comment]
基本概念搞清楚，还有readme看一下。
